# Generated by Django 5.2.5 on 2025-09-08 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0005_event_is_approved_budget_budgetitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budgetitem',
            name='category',
        ),
        migrations.RemoveField(
            model_name='budgetitem',
            name='description',
        ),
        migrations.AddField(
            model_name='budgetitem',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
